AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::299414552714:role/LabRole
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  PhotoProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: photo_processor/
      Handler: app.lambda_handler
      Runtime: python3.9
      Tracing: Active
      Role: arn:aws:iam::299414552714:role/LabRole
      Events:
        PhotoUploadSQSEvent:
          Type: SQS
          Properties:
            Queue: "arn:aws:sqs:us-east-1:299414552714:sqs-photo"
            BatchSize: 1

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  PhotoProcessorFunction:
    Description: "Photo Processor Lambda Function ARN"
    Value: !GetAtt PhotoProcessorFunction.Arn
