version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: PostgreSQL
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cnsd-bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
