version: '3.8'
name: cnsd-bank

services:
  postgres:
    image: postgres:latest
    container_name: PostgreSQL
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cnsd-bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: PG-Admin
    depends_on:
      - postgres
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_SERVER_JSON_FILE: /pgadmin/servers.json
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  application:
    image: "cnsd-bank"
    container_name: CNSD-Bank-Application
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cnsd-bank

volumes:
  postgres-data:
  pgadmin-data: