name: Feature pipeline

env:
  ASSIGNMENT_PATH: ${{ vars.RELEASE_PATH }}

on:
  push:
    branches: [ "feature**" ]
    paths:
      - 'module-1/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean install --file pom.xml
      working-directory: ${{ env.ASSIGNMENT_PATH }}

    - name: Upload Jacoco code report
      uses: actions/upload-artifact@v2
      with:
        name: cnsd-bank-jacoco-report
        path: ${{ env.ASSIGNMENT_PATH }}/target/site/jacoco

    - name: Upload PITest code report
      uses: actions/upload-artifact@v2
      with:
        name: cnsd-bank-pitest-report
        path: ${{ env.ASSIGNMENT_PATH }}/target/pit-reports

    - name: Sonarcube analysis
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=jordybronowicki37-CNSD \
        -Dsonar.host.url=https://sonar.cloud-native-minor.it \
        -Dsonar.login=${{ secrets.SONARCUBE_SECRET }} \
        -Dsonar.branch.name=$CI_BRANCH_NAME
      working-directory: ${{ env.ASSIGNMENT_PATH }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cnsd-bank:$GITHUB_RUN_NUMBER
      working-directory: ${{ env.ASSIGNMENT_PATH }}
