name: Publish Docker image with Maven

on:
  workflow_dispatch:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package --file ./module-1/opdracht_2_4/pom.xml
    - name: Build the Docker image
      run: docker build . --file ./module-1/opdracht_2_4/Dockerfile --tag cnsd-bank:$(date +%s)
